### ISSUE TITLE
Download counts enhancement request

### ISSUE THREAD

**Issue by masudk** [lulibrary/puree#1]
Can we add the download statistics API for datasets in there to retrieve at least the following?

title
uuid
downloads
person(s)
date

**Comment by aalbinclark** [comment]
[Download](../wiki/Download) count was added in 0.14.0. However, there is no additional data (such as a timestamp) in the Pure API response to provide any context. There is a renderedItem element in addition to the downloads attribute but this is simply all the [Dataset](../wiki/Dataset) metadata which is already available.
