### ISSUE TITLE
Person UUID is a Nokogiri::XML::Attr Object

### ISSUE THREAD

**Issue by geekscruff** [lulibrary/puree#2]
Hi Adrian,

In v. 0.16.0 the person uuid is a Nokogiri::XML::Attr Object rather than a string. I'm guessing this is a bug? It breaks trying to parse the json.

eg. from a dataset
 "person"=>{"internal"=>[{"name"=>{"first"=>"FIRST", "last"=>"LAST"}, "role"=>"Creator", "uuid"=>#<Nokogiri::XML::Attr:0x3fef71eb3584 name="uuid" value="UUID">}]

Cheers :)

Julie

**Comment by aalbinclark** [comment]
Hi Julie

Well spotted!

0.16.1 updates Dataset, Project, and Publication to return the expected text rather than a Nokogiri object.

Adrian

**Comment by geekscruff** [comment]
Brilliant :+1:
